# -*- coding: utf-8 -*-
"""Task06_2025.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GKS6qAm9T4y76LWtB8ZP-ToTFBSDENE_

**Task 06: Modifying RDF(s)**
"""

# !pip install rdflib

import urllib.request
# Commenting out network requests if you already have the file locally for the PR
# url = 'https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/refs/heads/master/Assignment4/course_materials/python/validation.py'
# urllib.request.urlretrieve(url, 'validation.py')
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/master/Assignment4/course_materials"

"""Import RDFLib main methods"""

from rdflib import Graph, Namespace, Literal, XSD
from rdflib.namespace import RDF, RDFS
from validation import Report

g = Graph()
# Note: The assignment asks to create new prefixes in Task 6.0, 
# so we will handle the binding there correctly.
r = Report()

"""Create a new class named Researcher"""

# NOTE: The instructions imply re-defining the namespace in 6.0, 
# but for the initial snippet we keep it as is.
ns = Namespace("http://mydomain.org#")
g.add((ns.Researcher, RDF.type, RDFS.Class))
for s, p, o in g:
  print(s,p,o)

"""**Task 6.0: Create new prefixes for "ontology" and "person" as shown in slide 14 of the Slidedeck 01a.RDF(s)-SPARQL shown in class.**"""

# TO DO
# Setting up the namespaces as typically required in this course (Slide 14 reference)
ns = Namespace("http://example.org/ontology#") # Prefix for the ontology (schema)
ns_person = Namespace("http://example.org/person#") # Prefix for the data (individuals)

# Binding them to the graph so the output looks clean (ns: and person:)
g.namespace_manager.bind('ns', ns, override=True)
g.namespace_manager.bind('person', ns_person, override=True)


"""**TASK 6.1: Reproduce the taxonomy of classes shown in slide 34 in class (all the classes under "Vocabulario", Slidedeck: 01a.RDF(s)-SPARQL). Add labels for each of them as they are in the diagram (exactly) with no language tags. Remember adding the correct datatype (xsd:String) when appropriate**"""

# TO DO
# Taxonomy: Person -> Researcher -> (Professor, PhDStudent). And University.

# 1. Person
g.add((ns.Person, RDF.type, RDFS.Class))
g.add((ns.Person, RDFS.label, Literal("Person", datatype=XSD.string)))

# 2. Researcher (SubClass of Person)
g.add((ns.Researcher, RDF.type, RDFS.Class))
g.add((ns.Researcher, RDFS.subClassOf, ns.Person))
g.add((ns.Researcher, RDFS.label, Literal("Researcher", datatype=XSD.string)))

# 3. Professor (SubClass of Researcher)
g.add((ns.Professor, RDF.type, RDFS.Class))
g.add((ns.Professor, RDFS.subClassOf, ns.Researcher))
g.add((ns.Professor, RDFS.label, Literal("Professor", datatype=XSD.string)))

# 4. PhDStudent (SubClass of Researcher)
g.add((ns.PhDStudent, RDF.type, RDFS.Class))
g.add((ns.PhDStudent, RDFS.subClassOf, ns.Researcher))
g.add((ns.PhDStudent, RDFS.label, Literal("PhDStudent", datatype=XSD.string)))

# 5. University (Stand alone class in the diagram)
g.add((ns.University, RDF.type, RDFS.Class))
g.add((ns.University, RDFS.label, Literal("University", datatype=XSD.string)))

# Visualize the results
for s, p, o in g:
  print(s,p,o)

# Validation. Do not remove
r.validate_task_06_01(g)

"""**TASK 6.2: Add the 3 properties shown in slide 36. Add labels for each of them (exactly as they are in the slide, with no language tags), and their corresponding domains and ranges using RDFS. Remember adding the correct datatype (xsd:String) when appropriate. If a property has no range, make it a literal (string)**"""

# TO DO
# Properties: worksAt, supervises, meets

# 1. worksAt (Domain: Researcher, Range: University)
g.add((ns.worksAt, RDF.type, RDF.Property))
g.add((ns.worksAt, RDFS.label, Literal("worksAt", datatype=XSD.string)))
g.add((ns.worksAt, RDFS.domain, ns.Researcher))
g.add((ns.worksAt, RDFS.range, ns.University))

# 2. supervises (Domain: Professor, Range: PhDStudent)
g.add((ns.supervises, RDF.type, RDF.Property))
g.add((ns.supervises, RDFS.label, Literal("supervises", datatype=XSD.string)))
g.add((ns.supervises, RDFS.domain, ns.Professor))
g.add((ns.supervises, RDFS.range, ns.PhDStudent))

# 3. meets (Domain: Person, Range: Person) - Wait, usually slide 36 implies generic person interaction
# Standard interpretation for this course:
g.add((ns.meets, RDF.type, RDF.Property))
g.add((ns.meets, RDFS.label, Literal("meets", datatype=XSD.string)))
g.add((ns.meets, RDFS.domain, ns.Person))
g.add((ns.meets, RDFS.range, ns.Person))

# Visualize the results
for s, p, o in g:
  print(s,p,o)

# Validation. Do not remove
r.validate_task_06_02(g)

"""**TASK 6.3: Create the individuals shown in slide 36 under "Datos". Link them with the same relationships shown in the diagram."**"""

# TO DO
# Individuals: Sara (Professor), Oscar (PhDStudent), UPM (University)
# Links: Sara supervises Oscar, Sara worksAt UPM, Oscar worksAt UPM

# Define individuals using the person namespace (ns_person) defined in 6.0
# Sara
g.add((ns_person.Sara, RDF.type, ns.Professor))

# Oscar
g.add((ns_person.Oscar, RDF.type, ns.PhDStudent))

# UPM
g.add((ns_person.UPM, RDF.type, ns.University))

# Relationships
# Sara worksAt UPM
g.add((ns_person.Sara, ns.worksAt, ns_person.UPM))
# Sara supervises Oscar
g.add((ns_person.Sara, ns.supervises, ns_person.Oscar))
# Oscar worksAt UPM
g.add((ns_person.Oscar, ns.worksAt, ns_person.UPM))


# Visualize the results
for s, p, o in g:
  print(s,p,o)

r.validate_task_06_03(g)

"""**TASK 6.4: Add to the individual person:Oscar the email address, given and family names. Use the properties already included in example 4 to describe Jane and John (https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/master/Assignment4/course_materials/rdf/example4.rdf). Do not import the namespaces, add them manually**"""

# TO DO
# We need to define the VCARD namespace manually as per example4.rdf
# Usually strictly: http://www.w3.org/2001/vcard-rdf/3.0#
vcard_ns = Namespace("http://www.w3.org/2001/vcard-rdf/3.0#")

# Properties to add: Given, Family, EMAIL
# Note: Values are strings (Literals)

# Given Name
g.add((ns_person.Oscar, vcard_ns.Given, Literal("Oscar", datatype=XSD.string)))

# Family Name
g.add((ns_person.Oscar, vcard_ns.Family, Literal("Martinez", datatype=XSD.string))) # Generic surname

# Email
g.add((ns_person.Oscar, vcard_ns.EMAIL, Literal("oscar@example.org", datatype=XSD.string)))

# Visualize the results
for s, p, o in g:
  print(s,p,o)

# Validation. Do not remove
r.validate_task_06_04(g)
r.save_report("_Task_06")