# -*- coding: utf-8 -*-
"""Task07_2025.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13zP7djRTBeG5tsTNq-mV-TGtIeDmqV7W

**Task 07: Querying RDF(s)**
"""

# !pip install rdflib
import urllib.request
# Commented out to avoid downloading every time you run the script locally
# url = 'https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/refs/heads/master/Assignment4/course_materials/python/validation.py'
# urllib.request.urlretrieve(url, 'validation.py')
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/master/Assignment4/course_materials"

from validation import Report

"""First let's read the RDF file"""

from rdflib import Graph, Namespace, Literal
from rdflib.namespace import RDF, RDFS
# Do not change the name of the variables
g = Graph()
g.namespace_manager.bind('ns', Namespace("http://somewhere#"), override=False)
g.namespace_manager.bind('vcard', Namespace("http://www.w3.org/2001/vcard-rdf/3.0#"), override=False)
g.parse(github_storage+"/rdf/data06.ttl", format="TTL")
report = Report()

"""**TASK 7.1a: For all classes, list each classURI. If the class belogs to another class, then list its superclass.**
**Do the exercise in RDFLib returning a list of Tuples: (class, superclass) called "result". If a class does not have a super class, then return None as the superclass**
"""

# TO DO
result = [] #list of tuples
# We search for all subjects that are of type RDFS.Class
for s, p, o in g.triples((None, RDF.type, RDFS.Class)):
    # For each class, we check if it has a subClassOf relation
    superclasses = list(g.objects(s, RDFS.subClassOf))
    if len(superclasses) > 0:
        for sc in superclasses:
            result.append((s, sc))
    else:
        result.append((s, None))

# Visualize the results
for r in result:
  print(r)

## Validation: Do not remove
report.validate_07_1a(result)

"""**TASK 7.1b: Repeat the same exercise in SPARQL, returning the variables ?c (class) and ?sc (superclass)**"""

# TO DO
# We use OPTIONAL to include classes that do not have a superclass
query = """
    SELECT ?c ?sc WHERE {
        ?c rdf:type rdfs:Class .
        OPTIONAL { ?c rdfs:subClassOf ?sc }
    }
"""

for r in g.query(query):
  print(r.c, r.sc)

## Validation: Do not remove
report.validate_07_1b(query,g)

"""**TASK 7.2a: List all individuals of "Person" with RDFLib (remember the subClasses). Return the individual URIs in a list called "individuals"**"""

# NOTE: The prompt had a different namespace here, but data06.ttl usually uses http://somewhere# for Person.
# We will use the correct namespace bound to the graph.
ns = Namespace("http://somewhere#")

# variable to return
individuals = []

# 1. Direct instances of Person
for s, p, o in g.triples((None, RDF.type, ns.Person)):
    individuals.append(s)

# 2. Instances of subclasses of Person (manual inference)
# First, find all subclasses of Person
subclasses = set()
# We look for direct subclasses (and assuming depth 1 for this simple dataset, 
# but a recursive function is safer usually. Here we do simple iteration).
for s, p, o in g.triples((None, RDFS.subClassOf, ns.Person)):
    subclasses.add(s)
    # Check for subclasses of subclasses (if any)
    for s2, p2, o2 in g.triples((None, RDFS.subClassOf, s)):
        subclasses.add(s2)

# Now find instances of those subclasses
for sc in subclasses:
    for s, p, o in g.triples((None, RDF.type, sc)):
        individuals.append(s)

# Ensure uniqueness
individuals = list(set(individuals))

# visualize results
for i in individuals:
  print(i)

# validation. Do not remove
report.validate_07_02a(individuals)

"""**TASK 7.2b: Repeat the same exercise in SPARQL, returning the individual URIs in a variable ?ind**"""

# TO DO
# using property path subClassOf* to get Person and all its subclasses
query = """
    PREFIX ns: <http://somewhere#>
    SELECT DISTINCT ?ind WHERE {
        ?ind rdf:type ?class .
        ?class rdfs:subClassOf* ns:Person .
    }
"""

for r in g.query(query):
  print(r.ind)
# Visualize the results

## Validation: Do not remove
report.validate_07_02b(g, query)

"""**TASK 7.3: List the name and type of those who know Rocky (in SPARQL only). Use name and type as variables in the query**"""

# TO DO
# Assuming Rocky is ns:RockySmith and the property is foaf:knows based on data06.ttl standard
query = """
    PREFIX ns: <http://somewhere#>
    PREFIX foaf: <http://xmlns.com/foaf/0.1/>
    SELECT ?name ?type WHERE {
        ?s foaf:knows ns:RockySmith .
        ?s foaf:name ?name .
        ?s rdf:type ?type .
    }
"""

# Visualize the results
for r in g.query(query):
  print(r.name, r.type)

## Validation: Do not remove
report.validate_07_03(g, query)

"""**Task 7.4: List the name of those entities who have a colleague with a dog, or that have a collegue who has a colleague who has a dog (in SPARQL). Return the results in a variable called name**"""

# TO DO
# We look for a colleague (distance 1 or 2) who has a relation to a Dog.
# We assume the relation "colleague" is ns:colleague (as per typical exam data)
# We assume "with a dog" means having a relation to an instance of ns:Dog
query = """
    PREFIX ns: <http://somewhere#>
    PREFIX foaf: <http://xmlns.com/foaf/0.1/>
    SELECT DISTINCT ?name WHERE {
        ?s foaf:name ?name .
        # Path 1: Direct colleague has a dog
        {
            ?s ns:colleague ?c .
            ?c ?p ?dog .
            ?dog rdf:type ns:Dog .
        }
        UNION
        # Path 2: Colleague of colleague has a dog
        {
            ?s ns:colleague ?c1 .
            ?c1 ns:colleague ?c2 .
            ?c2 ?p ?dog .
            ?dog rdf:type ns:Dog .
        }
    }
"""

for r in g.query(query):
  print(r.name)

# Visualize the results

## Validation: Do not remove
report.validate_07_04(g,query)
report.save_report("_Task_07")